apiVersion: v1
kind: Service
metadata:
  name: {{ include "quiz-builder.backend.name" . }}
  labels:
    {{- include "quiz-builder.labels" . | nindent 4 }}
    app: {{ include "quiz-builder.backend.name" . }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "quiz-builder.backend.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.backend.service.sessionAffinity | default "None" }}
